"""empty message

Revision ID: 30e51518114a
Revises: 3d8294c23148
Create Date: 2018-10-15 23:05:43.838854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e51518114a'
down_revision = '3d8294c23148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('provider_user_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(), nullable=True))
        batch_op.create_unique_constraint('unique_oauth_id', ['oauth_provider', 'provider_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint('unique_oauth_id', type_='unique')
        batch_op.drop_column('access_token')
        batch_op.drop_column('provider_user_id')
        batch_op.drop_column('oauth_provider')
    # ### end Alembic commands ###
