"""empty message

Revision ID: 30e51518114a
Revises: 3d8294c23148
Create Date: 2018-10-15 23:05:43.838854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e51518114a'
down_revision = '3d8294c23148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_provider', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('provider_user_id', sa.String(), nullable=True))
    op.create_unique_constraint('unique_oauth_id', 'user', ['oauth_provider', 'provider_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_oauth_id', 'user', type_='unique')
    op.drop_column('user', 'provider_user_id')
    op.drop_column('user', 'oauth_provider')
    # ### end Alembic commands ###
